version: 2
jobs:
  test:
    working_directory: ~/builds
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  build:
    working_directory: ~/builds
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: build-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - public
  deploy:
    working_directory: ~/builds
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
